- name: install k8s node dependencies
  apt:

    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - gpg
      - software-properties-common
    state: latest

- name: disable swap on k8s nodes for this session
  become: true
  command: swapoff -a
  changed_when: false

- name: disable swap on k8s nodes permanently
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Add CRIO repository
  block:

    - name: Download cri-o signing key
      get_url:
        url: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key
        dest: /etc/apt/keyrings/crio.gpg_armored

    - name: De-Armor crio key
      shell: "gpg --dearmor < /etc/apt/keyrings/crio.gpg_armored > /etc/apt/keyrings/crio.gpg"
      args:
        creates: /etc/apt/keyrings/crio.gpg

    - name: Add crio repository
      apt_repository: 
        repo: "deb [signed-by=/etc/apt/keyrings/crio.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /"

- name: Install cri-o
  apt:
    name: cri-o
    state: present

- name: Add k8s repository
  block:

    - name: Download k8s signing key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg_armored
    
    - name: De-Armor k8s key
      shell: "gpg --dearmor < /etc/apt/keyrings/kubernetes-apt-keyring.gpg_armored > /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"

- name: Install k8s dependencies
  apt:
    name: 
      - kubelet
      - kubeadm
    state: present

- name: Hold k8s deps
  shell: apt-mark hold kubelet kubeadm
  changed_when: false

- name: start crio service
  service:
    name: crio
    state: started
    enabled: yes

- name: start kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Check for kubelet config
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeletconf

- name: Join cluster
  shell: kubeadm join 192.168.60.4:6443 --token abcdef.1212121212121212 --discovery-token-unsafe-skip-ca-verification 
  when: not kubeletconf.stat.exists