- name: Install kubectl
  apt:
    name: kubectl
    state: present

- name: Hold k8s deps
  shell: apt-mark hold kubectl 
  changed_when: false

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true